import argparse
import json
import random
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run simplified ReCom on SeaWulf input artifacts generated by generate_seawulf_inputs.py."
        )
    )
    parser.add_argument("legacy_steps", nargs="?", type=int, help="Backward-compatible positional steps arg.")
    parser.add_argument("legacy_output", nargs="?", help="Backward-compatible positional output arg.")
    parser.add_argument("--state", default="AZ", help="Two-letter state code (AZ or CO).")
    parser.add_argument("--steps", type=int, default=10, help="Number of attempted ReCom steps.")
    parser.add_argument(
        "--input-root",
        default="../results/seawulf_inputs",
        help="Root directory that contains <STATE>/<STATE>_graph.json and precinct_attributes.json.",
    )
    parser.add_argument(
        "--output",
        default="../results/recom_plans.json",
        help="Output file for generated plans and summary.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")
    parser.add_argument(
        "--pop-tolerance-pct",
        type=float,
        default=0.05,
        help="Allowed percent deviation from half-population in each recombined pair (default 0.05).",
    )
    parser.add_argument(
        "--vra-group-field",
        default=None,
        help=(
            "Optional CVAP field for constrained runs (example: CVAP_HSP24). "
            "When set with --vra-min-districts, candidate plans that violate this floor are rejected."
        ),
    )
    parser.add_argument(
        "--vra-min-districts",
        type=int,
        default=None,
        help="Minimum number of opportunity districts required when VRA constraint mode is enabled.",
    )
    parser.add_argument(
        "--vra-threshold",
        type=float,
        default=0.5,
        help="Opportunity threshold for group share in a district (default 0.5).",
    )
    args = parser.parse_args()
    if args.legacy_steps is not None:
        args.steps = args.legacy_steps
    if args.legacy_output is not None:
        args.output = args.legacy_output
    return args


def compute_ensemble_summary(plans):
    if not plans:
        return {}
    r_vals = [p["split"]["R"] for p in plans]
    d_vals = [p["split"]["D"] for p in plans]
    return {
        "avg_R": sum(r_vals) / len(r_vals),
        "avg_D": sum(d_vals) / len(d_vals),
        "min_R": min(r_vals),
        "max_R": max(r_vals),
        "min_D": min(d_vals),
        "max_D": max(d_vals),
    }


def load_state_graph(state: str, input_root: str):
    """
    Load a real precinct graph and attributes from Prepro-6 outputs.

    Files expected under <input_root>/<STATE>/:
    - <STATE>_graph.json
    - <STATE>_precinct_attributes.json
    """
    state_upper = state.strip().upper()
    state_dir = Path(input_root) / state_upper
    graph_path = state_dir / f"{state_upper}_graph.json"
    attrs_path = state_dir / f"{state_upper}_precinct_attributes.json"

    with graph_path.open("r", encoding="utf-8") as handle:
        graph_payload = json.load(handle)
    with attrs_path.open("r", encoding="utf-8") as handle:
        attrs_payload = json.load(handle)

    if not isinstance(attrs_payload, list):
        raise ValueError(f"Unexpected precinct attributes format: {attrs_path}")

    attrs_by_geoid = {
        str(row.get("GEOID")): row
        for row in attrs_payload
        if isinstance(row, dict) and row.get("GEOID") is not None
    }

    adjacency = graph_payload.get("adjacency", {})
    if not isinstance(adjacency, dict):
        raise ValueError(f"Unexpected graph adjacency format: {graph_path}")

    # In-memory graph uses:
    # G["adj"]: dict[node] -> set(neighbor nodes)
    # G["nodes"]: dict[node] -> attribute dict
    G = {"adj": {}, "nodes": {}}

    for geoid in adjacency.keys():
        node = str(geoid)
        G["adj"].setdefault(node, set())

    for geoid, neighbors in adjacency.items():
        a = str(geoid)
        if not isinstance(neighbors, list):
            continue
        for neighbor in neighbors:
            b = str(neighbor)
            if a == b:
                continue
            G["adj"].setdefault(a, set()).add(b)
            G["adj"].setdefault(b, set()).add(a)

    # Attach node attributes needed by run logic.
    for node in G["adj"].keys():
        row = attrs_by_geoid.get(node, {})
        district = str(row.get("district_number") or "00").zfill(2)
        dem_votes = float(row.get("votes_dem") or 0.0)
        rep_votes = float(row.get("votes_rep") or 0.0)
        cvap_total = float(row.get("CVAP_TOT24") or 0.0)
        fallback_pop = float(row.get("votes_total") or 1.0)
        population = cvap_total if cvap_total > 0 else max(1.0, fallback_pop)
        G["nodes"][node] = {
            "district": district,
            "dem_votes": dem_votes,
            "rep_votes": rep_votes,
            "population": population,
            "raw": row,
        }
        # Keep all raw attributes for future SeaWulf use-cases (VRA metrics, etc.).
        G["nodes"][node]["raw"] = row

    return G


def graph_nodes(G):
    return G["nodes"].keys()


def graph_edges(G):
    edges = []
    for a, neighbors in G["adj"].items():
        for b in neighbors:
            if a < b:
                edges.append((a, b))
    return edges


def induced_subgraph_adj(G, subset):
    subset_set = set(subset)
    return {node: {nbr for nbr in G["adj"].get(node, set()) if nbr in subset_set} for node in subset_set}


def is_connected_adj(adj):
    if not adj:
        return False
    start = next(iter(adj.keys()))
    seen = set([start])
    stack = [start]
    while stack:
        cur = stack.pop()
        for nbr in adj.get(cur, set()):
            if nbr not in seen:
                seen.add(nbr)
                stack.append(nbr)
    return len(seen) == len(adj)


def spanning_tree_edges(adj, rng):
    # Randomized DFS spanning tree over the induced pair subgraph.
    start = next(iter(adj.keys()))
    seen = set([start])
    stack = [start]
    tree = []
    while stack:
        cur = stack.pop()
        neighbors = list(adj.get(cur, set()))
        rng.shuffle(neighbors)
        for nbr in neighbors:
            if nbr in seen:
                continue
            seen.add(nbr)
            stack.append(nbr)
            tree.append((cur, nbr))
    return tree


def component_from_tree_without_edge(tree_adj, start):
    seen = set([start])
    stack = [start]
    while stack:
        cur = stack.pop()
        for nbr in tree_adj.get(cur, set()):
            if nbr not in seen:
                seen.add(nbr)
                stack.append(nbr)
    return seen


def connected_components_adj(adj):
    remaining = set(adj.keys())
    components = []
    while remaining:
        start = next(iter(remaining))
        comp = set([start])
        stack = [start]
        while stack:
            cur = stack.pop()
            for nbr in adj.get(cur, set()):
                if nbr not in comp:
                    comp.add(nbr)
                    stack.append(nbr)
        components.append(comp)
        remaining -= comp
    return components


def district_populations(G):
    pops = {}
    for node in graph_nodes(G):
        d = G["nodes"][node]["district"]
        pops[d] = pops.get(d, 0.0) + float(G["nodes"][node].get("population", 0.0))
    return {k: round(v, 4) for k, v in sorted(pops.items())}


def export_plan(G):
    return {str(node): G["nodes"][node]["district"] for node in sorted(graph_nodes(G))}


def compute_district_winners(G):
    totals = {}
    for n in graph_nodes(G):
        d = G["nodes"][n]["district"]
        if d not in totals:
            totals[d] = {"D": 0.0, "R": 0.0}
        totals[d]["D"] += float(G["nodes"][n].get("dem_votes", 0.0))
        totals[d]["R"] += float(G["nodes"][n].get("rep_votes", 0.0))
    winners = {}
    for d in sorted(totals.keys()):
        winners[d] = "D" if totals[d]["D"] > totals[d]["R"] else "R"
    return winners


def compute_plan_split(winners):
    r = sum(1 for w in winners.values() if w == "R")
    d = sum(1 for w in winners.values() if w == "D")
    return {"R": r, "D": d}


def find_adjacent_district_pairs(G):
    pairs = set()
    for u, v in graph_edges(G):
        du = G["nodes"][u]["district"]
        dv = G["nodes"][v]["district"]
        if du != dv:
            pairs.add(tuple(sorted((du, dv))))
    return sorted(pairs)


def population_of_nodes(G, nodes):
    return sum(float(G["nodes"][n].get("population", 0.0)) for n in nodes)


def count_opportunity_districts(G, group_field: str, threshold: float):
    district_group_totals = {}
    district_total_cvap = {}
    for node in graph_nodes(G):
        district = G["nodes"][node]["district"]
        raw = G["nodes"][node].get("raw") or {}
        group_val = float(raw.get(group_field) or 0.0)
        total_cvap = float(raw.get("CVAP_TOT24") or 0.0)
        district_group_totals[district] = district_group_totals.get(district, 0.0) + group_val
        district_total_cvap[district] = district_total_cvap.get(district, 0.0) + total_cvap

    count = 0
    for district in district_total_cvap.keys():
        denom = district_total_cvap[district]
        share = (district_group_totals[district] / denom) if denom > 0 else 0.0
        if share >= threshold:
            count += 1
    return count


def one_recom_step(
    G,
    rng,
    pop_tolerance_pct,
    vra_group_field=None,
    vra_min_districts=None,
    vra_threshold=0.5,
):
    """
    Perform one simplified ReCom step on a real precinct graph.

    Process:
    1) Pick adjacent district pairs.
    2) Merge each pair, build a spanning tree.
    3) Remove one tree edge to split into two connected components.
    4) Accept the split if population balance (and optional VRA constraints) pass.
    """
    pairs = find_adjacent_district_pairs(G)
    rng.shuffle(pairs)
    for d1, d2 in pairs:
        sub_nodes = [n for n in graph_nodes(G) if G["nodes"][n]["district"] in (d1, d2)]
        if not sub_nodes:
            continue

        sub_adj = induced_subgraph_adj(G, sub_nodes)
        candidate_components = connected_components_adj(sub_adj)
        rng.shuffle(candidate_components)
        for component_nodes in candidate_components:
            component_districts = {G["nodes"][n]["district"] for n in component_nodes}
            # ReCom split only makes sense if both districts are present in this component.
            if d1 not in component_districts or d2 not in component_districts:
                continue

            component_adj = induced_subgraph_adj(G, component_nodes)
            if not is_connected_adj(component_adj):
                continue

            total_pop = population_of_nodes(G, component_nodes)
            target = total_pop / 2.0

            edges = spanning_tree_edges(component_adj, rng)
            rng.shuffle(edges)

            # Adaptive tolerance keeps runs moving on harder district pairs.
            # Last pass uses no balance filter, but still preserves contiguity and optional VRA checks.
            tolerance_passes = [
                target * pop_tolerance_pct,
                target * pop_tolerance_pct * 2.0,
                target * pop_tolerance_pct * 4.0,
                None,
            ]

            for tolerance in tolerance_passes:
                for u, v in edges:
                    # Build tree adjacency and remove one edge to split into two pieces.
                    tree_adj = {n: set() for n in component_nodes}
                    for a, b in edges:
                        if (a == u and b == v) or (a == v and b == u):
                            continue
                        tree_adj[a].add(b)
                        tree_adj[b].add(a)

                    comp1 = component_from_tree_without_edge(tree_adj, u)
                    comp2 = set(component_nodes) - comp1
                    if not comp1 or not comp2:
                        continue

                    pop1 = population_of_nodes(G, comp1)
                    pop2 = population_of_nodes(G, comp2)
                    if tolerance is not None:
                        if abs(pop1 - target) > tolerance or abs(pop2 - target) > tolerance:
                            continue

                    # Tentatively apply split.
                    for n in comp1:
                        G["nodes"][n]["district"] = d1
                    for n in comp2:
                        G["nodes"][n]["district"] = d2

                    # Optional VRA-constrained mode for SeaWulf-3 style runs.
                    if vra_group_field and vra_min_districts is not None:
                        opportunity = count_opportunity_districts(G, vra_group_field, vra_threshold)
                        if opportunity < int(vra_min_districts):
                            # Revert and keep searching.
                            for n in comp1:
                                G["nodes"][n]["district"] = d2
                            for n in comp2:
                                G["nodes"][n]["district"] = d1
                            continue

                    return True
    return False


def generate_plans(
    state,
    steps,
    input_root,
    seed,
    pop_tolerance_pct,
    vra_group_field=None,
    vra_min_districts=None,
    vra_threshold=0.5,
    worker_id=None,
):
    rng = random.Random(seed)
    G = load_state_graph(state=state, input_root=input_root)

    plans = []
    for step in range(steps):
        success = one_recom_step(
            G,
            rng,
            pop_tolerance_pct,
            vra_group_field=vra_group_field,
            vra_min_districts=vra_min_districts,
            vra_threshold=vra_threshold,
        )
        if not success:
            print(f"Step {step + 1} failed")
            continue

        winners = compute_district_winners(G)
        split = compute_plan_split(winners)
        record = {
            "state": state,
            "worker": worker_id,
            "step": step + 1,
            "district_populations": district_populations(G),
            "winners": winners,
            "split": split,
            "assignment": export_plan(G),
        }
        plans.append(record)
        print(f"Step {step + 1} saved | Split: {split}")
    return plans


def main():
    args = parse_args()
    state = args.state.strip().upper()

    print(f"Running {args.steps} ReCom steps for state={state}...")
    plans = generate_plans(
        state=state,
        steps=args.steps,
        input_root=args.input_root,
        seed=args.seed,
        pop_tolerance_pct=args.pop_tolerance_pct,
        vra_group_field=args.vra_group_field,
        vra_min_districts=args.vra_min_districts,
        vra_threshold=args.vra_threshold,
    )

    summary = compute_ensemble_summary(plans) if plans else {}
    output = {
        "state": state,
        "num_plans": len(plans),
        "summary": summary,
        "plans": plans,
        "run_config": {
            "steps": args.steps,
            "input_root": args.input_root,
            "seed": args.seed,
            "pop_tolerance_pct": args.pop_tolerance_pct,
            "vra_group_field": args.vra_group_field,
            "vra_min_districts": args.vra_min_districts,
            "vra_threshold": args.vra_threshold,
        },
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2)
        handle.write("\n")
    print(f"Saved to {output_path}")


if __name__ == "__main__":
    main()
